name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Mambaforge  # Faster solver
          miniforge-version: latest
          activate-environment: csca-5642-tf-mac  # Choose a name for the CI env
          environment-file: conda-env-metal.yml  # Point to your YAML file
          use-mamba: true
      - name: Install pylint (if needed)
        shell: bash -l {0}
        run: mamba install pylint
      - name: Analysing the code with pylint
        shell: bash -l {0}
        run: |
          pylint $(git ls-files '*.py')